const headings = [
'Create a new Emial-List',
'Add a New List',
'Name the new List',
'Complete the Settings & Activate the List',
'List is Activated',
'This feature is only for Leadsleap Pro Upgrades',
'LL Free members can write their own Welcome Email',
'Email List Import code is list-eXfwGhZwu',
'Update your affiliate links in my Emails',
'Go to Next Step',
];
const images = [
"https://i.imgur.com/u8TQoHk.png",
"https://i.imgur.com/9IYc8qp.png",
"https://i.imgur.com/iiuevqk.png",
"https://i.imgur.com/Dd3RXs4.png",
"https://i.imgur.com/tzbDNDs.png",
"https://i.imgur.com/A9JFjKY.png",
"https://i.imgur.com/Kssy5Wo.png",
"https://i.imgur.com/ntSRDsM.png",
"https://i.imgur.com/2WDQuWA.png",
'https://i.imgur.com/6AIffkq.png',
];
const links = [
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
]; 