const headings = [
'Setup your LeadsLeap MainPage',
'Add a New Page',
'Name the new Page',
'LL MainPage Import Code is page-acWZVWdWG',
'LeadsLeap MainPage import is done',
'Open Page Editor',
'Update your Leadsleap Affiliate link',
'Update your ClickEngine Affiliate Link',
'Update your other 4 Traffic Affiliate links',
'Your LeadsLeap MainPage link is ready',
'Save anyone of the 2 Links',
'Go to Next Step',
];
const images = [
"https://i.imgur.com/lxETeuA.png",
"https://i.imgur.com/zgGN6QX.png",
"https://i.imgur.com/zwt3gA6.png",
"https://i.imgur.com/Dlaxbwp.png",
"https://i.imgur.com/dnCIP7P.png",
'https://i.imgur.com/zvsDpfM.png',
'https://i.imgur.com/y4IFcgM.png',
'https://i.imgur.com/K5AbaQL.png',
'https://i.imgur.com/xMGkGcP.png',
'https://i.imgur.com/nBhyBPk.png',
'https://i.imgur.com/CIGTzyW.png',
'https://i.imgur.com/rikzdIQ.png',
];
const links = [
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
]; 