const headings = [
'Setup EB OptionsPage',
'Add a New Page',
'Name the new Page',
'EB OptionsPage Import Code is page-aKZNVKCVk',
'Open Page Editor',
'Update your Automated MainPage link',
'Update your LeadsLeap MainPage Link',
'Your EB OptionsPage link is ready',
'Save anyone of the 2 Links',
'Go to Next Step',
];
const images = [
"https://i.imgur.com/EoirxkC.png",
"https://i.imgur.com/zgGN6QX.png",
"https://i.imgur.com/mGfgFJ4.png",
"https://i.imgur.com/4qwXLHR.png",
'https://i.imgur.com/0T1KrVG.png',
'https://i.imgur.com/OpnQ0WE.png',
'https://i.imgur.com/nuy3nfZ.png',
"https://i.imgur.com/R5S0TID.png",
'https://i.imgur.com/2nP80vA.png',
'https://i.imgur.com/SG7DbC9.png',
];
const links = [
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
"https://leadsleap.com/?r=rjsearn",
]; 