const headings = [
'Start The ClickEngine Subscription',
'Start from Anywhere',
'Complete your Subscription',
'Complete your Subscription',
'Complete your Subscription',
'This is your ClickEngine Rotator',
'Get your CE Affiliate Link from WP',
'Get your CE Affiliate Link from WP',
'Search your CE Purchased product',
'Request Vendor for Affiliate Link',
'Write Request for Affiliate Link',
'Save your CE AffiliateLink',
'Save your CE AffiliateLink',
'Go to Next Traffic Rotator',
];
const images = [
'https://i.imgur.com/Lo9Yc6M.png',
'https://i.imgur.com/FANOSSx.png',
'https://i.imgur.com/k08jLxS.png',
'https://i.imgur.com/t44QOqC.png',
'https://i.imgur.com/7xxpuDW.png',
'https://i.imgur.com/1DikuLh.png',
'https://i.imgur.com/NVlijlW.png',
'https://i.imgur.com/IOCnFPO.png',
'https://i.imgur.com/fAcyY86.png',
'https://i.imgur.com/AVBwan2.png',
'https://i.imgur.com/i0NLIZS.png',
'https://i.imgur.com/Yuy3iAK.png',
'https://i.imgur.com/jVj9TLf.png',
'https://i.imgur.com/3DKjk1w.png',
];
const links = [
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
"https://warriorplus.com/o2/a/pbyg3j/0",
];